server:
  port: ${gateway-server-port}

spring:
  application.name: ${application-name}
  cloud:
    gateway:
      routes:
        - id: resources
          uri: ${resource-server}/messages
          predicates:
            Path=/messages/**
          filters:
            TokenRelay=

        - id: info1
          uri: ${resource-server}/user/info
          predicates:
            Path=/info/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        provider:
          my-provider:
            issuer-uri: ${auth-server}/realms/${realm}
        #            issuer-uri: https://localhost:8443/realms/${realm}
        registration:
          gateway:
            provider: my-provider
            client-id: ${clientID}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "${gateway-server}/login/oauth2/code/{registrationId}"
            scope: openid, email, profile, roles, messages.read

# example URL
# http://backend-gateway-client:8083/messages
