server:
  port: 8543
  ssl:
    certificate: classpath:backend-gateway-clientcert.pem
    certificate-private-key: classpath:backend-gateway-clientkey.pem
#    trust-store: classpath:backend-gateway-client-keystore.jks
#    trust-store-password: password99

spring:
  application.name: backend-gateway-client
  cloud:
    gateway:
      routes:
        - id: resources
          uri: https://backend-resources:8643/messages
          predicates:
            Path=/messages/**
          filters:
            TokenRelay=

        - id: info1
          uri: https://backend-resources:8643/user
          predicates:
            Path=/info/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        provider:
          my-provider:
            issuer-uri: https://sso.billview.com.au/realms/myfirsttest
        registration:
          gateway:
            provider: my-provider
            client-id: homedemo1
            client-secret: VuS3dVrR3Vvb0ISizwk3DR2JdBQfNDfY
            authorization-grant-type: authorization_code
            redirect-uri: "https://backend-gateway-client:8543/login/oauth2/code/{registrationId}"
            scope: openid, email, profile, roles, message.read

# example URL
# https://backend-gateway-client:8543/messages
