server:
  port: 8083

spring:
  application.name: backend-gateway-client
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://backend-resources:8082/messages
          predicates:
            Path=/messages/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: my_client
            client-secret: H6KarpzuCsqnppPFGwzINtnzQJmJORug
            authorization-grant-type: authorization_code
            redirect-uri: "http://backend-gateway-client:8083/login/oauth2/code/{registrationId}"
            scope: openid, messages.read
        provider:
          my-provider:
            issuer-uri: http://backend-auth:8080/auth/realms/my_realm
#            issuer-uri: https://localhost:8443/auth/realms/my_realm

# example URL
# http://backend-gateway-client:8083/messages
