server:
  port: 8083

spring:
  application.name: backend-gateway-client
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://backend-resources:8082/messages
          predicates:
            Path=/messages/**
          filters:
            TokenRelay=
        - id: info
          uri: http://backend-resources:8082/user/info
          predicates:
            Path=/user/info/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        provider:
          my-provider:
            issuer-uri: http://backend-auth:8080/auth/realms/my_realm
        #            issuer-uri: https://localhost:8443/auth/realms/my_realm
        registration:
          gateway:
            provider: my-provider
            client-id: my_client
            client-secret: H6KarpzuCsqnppPFGwzINtnzQJmJORug
            authorization-grant-type: authorization_code
            redirect-uri: "http://backend-gateway-client:8083/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
              - roles
              - messages.read

# example URL
# http://backend-gateway-client:8083/messages
