version: '3.7'

services:
  #-------------- Keycloak 20.0.3 --------------
  # in this container runs keycloak runs as user keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    restart: unless-stopped
    environment:
      TZ: Australia/Perth
      KC_DB: mysql
      KC_DB_URL_HOST: "${KEYCLOAK_HOST}"
      KC_DB_URL_DATABASE: "${KEYCLOAK_DATABASE}"
      KC_DB_USERNAME: "${KEYCLOAK_USER}"
      KC_DB_PASSWORD: "${KEYCLOAK_PASSWORD}"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      KC_HEALTH_ENABLED: "true"
      #    KC_HOSTNAME_URL: https://sso.billview.com.au
      KC_HOSTNAME_STRICT: "false"
      KC_LOG_LEVEL: info
      KC_LOG: file
      #    KC_HTTP_RELATIVE_PATH: /auth
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
      KC_HTTP_ENABLED: "false"
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: "true"
    #     KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      - start
    volumes:

      #  - ./nginx/cert/letsencrypt/live/example.com/privkey.pem:/opt/keycloak/conf/server.key.pem
      #  - ./nginx/cert/letsencrypt/live/example.com/fullchain.pem:/opt/keycloak/conf/server.crt.pem

      - /etc/letsencrypt/live/sso.billview.com.au/privkey.pem:/opt/keycloak/conf/server.key.pem:ro
      - /etc/letsencrypt/live/sso.billview.com.au/fullchain.pem:/opt/keycloak/conf/server.crt.pem:ro
      #  - ./certs/privkey.pem:/opt/keycloak/conf/server.key.pem:ro
      #  - ./certs/fullchain.pem:/opt/keycloak/conf/server.crt.pem:ro

      - ./conf/keycloak.conf:/opt/keycloak/conf/keycloak.conf:ro
      #   - ./keycloak/providers:/opt/keycloak/providers
      - ./data:/opt/keycloak/data
      - ./themes:/opt/keycloak/themes
    ports:
      # - 80:8080
      - 18443:8443
  #-------------- nginx -------------------
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/sso.billview.com.au/privkey.pem:/etc/nginx/cert/privkey.pem:ro
      - /etc/letsencrypt/live/sso.billview.com.au/fullchain.pem:/etc/nginx/cert/fullchain.pem:ro
      - ./www:/data/www
    ports:
      - 80:80
      - 443:443
    external_links:
      - keycloak
    depends_on:
      keycloak:
        condition: service_healthy

