version: '3.7'

volumes:
  mysql_data:
    name: mysql_kc_dev_data
    driver: local

services:
  mysql:
    container_name: mysql_kc_dev
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  #-------------- Keycloak 20.0.3 --------------
  # in this container runs keycloak runs as user keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      KC_HEALTH_ENABLED: "true"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/demo/certs/localhostcert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/demo/certs/localhostkey.pem
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: start-dev
    volumes:
      - ./certs:/opt/keycloak/demo/certs
    ports:
      - 8070:8080
      - 8443:8443
    depends_on:
      - mysql
  #-------------- PHPMYADMIN --------------
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8090:80
    environment:
      # we specify that we connect to an arbitrary server with the flag below
      # "arbitrary" means you're able to specify which database server to use on login page of phpmyadmin
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
