server:
  port: 8082

spring:
  application.name: backend-resources
  # the current backend is configured to be used as a resource server
  # then, I must indicate the URI of the backend-auth to be used and which token to be used
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://backend-auth:8070/realms/${realm}
          jwk-set-uri: http://backend-auth:8070/realms/${realm}/protocol/openid-connect/certs

#        opaquetoken:
#          introspection-uri: http:/backend-auth:8070/realms/${realm}/protocol/openid-connect/token/introspect
#          client-id: ${clientID}
#          client-secret: ${client-secret}
